import { Compass, Leaf, ShieldCheck } from "lucide-react";
import type { Partner } from "./types";

/**
 * Partner registry — the single source of truth for branding.
 *
 * To onboard a new partner, add ONE object to this array: an id, name, icon and
 * a light + dark token set (flat hex). Everything else (theme switching,
 * persistence, the switcher UI) picks it up automatically because the rest of
 * the app only ever reads semantic tokens, never a partner-specific value.
 */
export const PARTNERS: Partner[] = [
  {
    id: "aegis",
    name: "Aegis Assure",
    shortName: "Aegis",
    tagline: "Protection, simplified.",
    Icon: ShieldCheck,
    tokens: {
      light: {
        background: "#f7f9fc",
        foreground: "#14213a",
        surface: "#ffffff",
        "surface-foreground": "#14213a",
        muted: "#eef1f6",
        "muted-foreground": "#5b6678",
        border: "#dde3ec",
        input: "#d3dae6",
        ring: "#2647c9",
        primary: "#2647c9",
        "primary-foreground": "#ffffff",
        "primary-hover": "#1f3aa8",
        "primary-soft": "#e7ecfb",
        secondary: "#25304d",
        "secondary-foreground": "#ffffff",
        "secondary-hover": "#1b2540",
        accent: "#0aa2e8",
        "accent-foreground": "#ffffff",
        "accent-soft": "#e2f3fc",
      },
      dark: {
        background: "#0d1322",
        foreground: "#e8edf6",
        surface: "#141b2d",
        "surface-foreground": "#e8edf6",
        muted: "#1e2740",
        "muted-foreground": "#93a0b8",
        border: "#283149",
        input: "#2d3750",
        ring: "#5b78e6",
        primary: "#5b78e6",
        "primary-foreground": "#0d1322",
        "primary-hover": "#738ceb",
        "primary-soft": "#1c2647",
        secondary: "#d9e0f0",
        "secondary-foreground": "#0d1322",
        "secondary-hover": "#c4cee6",
        accent: "#38b6f0",
        "accent-foreground": "#0d1322",
        "accent-soft": "#15314a",
      },
    },
  },
  {
    id: "vitalcare",
    name: "VitalCare Health",
    shortName: "VitalCare",
    tagline: "Care that keeps up with you.",
    Icon: Leaf,
    tokens: {
      light: {
        background: "#f4faf7",
        foreground: "#0c2a22",
        surface: "#ffffff",
        "surface-foreground": "#0c2a22",
        muted: "#e7f2ec",
        "muted-foreground": "#4f6b62",
        border: "#d4e6dd",
        input: "#c9e0d4",
        ring: "#0f9d6e",
        primary: "#0f9d6e",
        "primary-foreground": "#ffffff",
        "primary-hover": "#0c8159",
        "primary-soft": "#def3ea",
        secondary: "#11453a",
        "secondary-foreground": "#ffffff",
        "secondary-hover": "#0c3a30",
        accent: "#27ae60",
        "accent-foreground": "#ffffff",
        "accent-soft": "#e0f5e8",
      },
      dark: {
        background: "#07140f",
        foreground: "#e6f2ec",
        surface: "#0d1f18",
        "surface-foreground": "#e6f2ec",
        muted: "#15281f",
        "muted-foreground": "#8aa89b",
        border: "#1f3329",
        input: "#24382d",
        ring: "#2bbd86",
        primary: "#2bbd86",
        "primary-foreground": "#07140f",
        "primary-hover": "#41c897",
        "primary-soft": "#123026",
        secondary: "#d4ece1",
        "secondary-foreground": "#07140f",
        "secondary-hover": "#bfe0d1",
        accent: "#34c46c",
        "accent-foreground": "#07140f",
        "accent-soft": "#103021",
      },
    },
  },
  {
    id: "orbit",
    name: "Orbit Cover",
    shortName: "Orbit",
    tagline: "Insurance for the journey ahead.",
    Icon: Compass,
    tokens: {
      light: {
        background: "#f9f7fd",
        foreground: "#1e1633",
        surface: "#ffffff",
        "surface-foreground": "#1e1633",
        muted: "#f0ecf8",
        "muted-foreground": "#635a78",
        border: "#e4ddf0",
        input: "#ddd4ec",
        ring: "#6d3bd4",
        primary: "#6d3bd4",
        "primary-foreground": "#ffffff",
        "primary-hover": "#5b2eb8",
        "primary-soft": "#ece2fb",
        secondary: "#2f2350",
        "secondary-foreground": "#ffffff",
        "secondary-hover": "#261c43",
        accent: "#d63c9d",
        "accent-foreground": "#ffffff",
        "accent-soft": "#fce2f1",
      },
      dark: {
        background: "#120c20",
        foreground: "#ece6f6",
        surface: "#1b1430",
        "surface-foreground": "#ece6f6",
        muted: "#261d40",
        "muted-foreground": "#a094bf",
        border: "#30264b",
        input: "#352a54",
        ring: "#9168e6",
        primary: "#9168e6",
        "primary-foreground": "#120c20",
        "primary-hover": "#a484eb",
        "primary-soft": "#241a40",
        secondary: "#ddd4f0",
        "secondary-foreground": "#120c20",
        "secondary-hover": "#c9bce6",
        accent: "#e667b4",
        "accent-foreground": "#120c20",
        "accent-soft": "#3a1c30",
      },
    },
  },
];

export const DEFAULT_PARTNER_ID = PARTNERS[0].id;

export const getPartner = (id: string): Partner =>
  PARTNERS.find((p) => p.id === id) ?? PARTNERS[0];
